# Generated by Django 4.2.4 on 2023-09-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_alter_candidate_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
