# Generated by Django 4.2.4 on 2023-09-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_vote_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
